FROM ruby:2.3

LABEL maintainer="eduardo.ufpb@gmail.com"

COPY spec/dependencias/texlive-abntex2.profile /tmp
WORKDIR /tmp

# Instala texlive
ADD http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz /tmp/
RUN tar -xf install-tl-unx.tar.gz && cd install-tl-* &&  ./install-tl -no-gui -profile ../texlive-abntex2.profile -no-verify-downloads
# adiciona latex ao caminho
ENV PATH $PATH:/usr/local/texlive/2017/bin/x86_64-linux
RUN rm -rf /tmp/install-tl-*

ENTRYPOINT /bin/bash
