selected_scheme scheme-basic
binary_x86_64-linux 1
collection-basic 1
option_w32_multi_user 0
option_letter 0
portable 0
option_doc 0
option_src 0
collection-basic 1
collection-fontsrecommended 1
collection-langportuguese 1
collection-latex 1
collection-latexextra 1
collection-latexrecommended 1
collection-publishers 1
collection-xetex 1
abntex2 1
latexmk 1
texlive.infra 1
texlive.infra.x86_64-linux 1
