selected_scheme scheme-small
texlive-publishers 1
texlive-lang-portuguese 1
texlive-latex-extra 1
texlive-fonts-recommended 1
collection-xetex 1
collection-latex 1
collection-latexextra 1
collection-latexrecommended 1
latexmk 1
option_letter 0
portable 0
option_doc 0
option_src 0
TEXLIVE_INSTALL_ENV_NOCHECK 1
